In [1]:
#Figure 3
import numpy as np 
import matplotlib.pyplot as plt

# specify circle parameters: centre ij and radius
nodes = np.zeros((100,100,8))
ci,cj=50,50

# Create index arrays to z
I,J=np.meshgrid(np.arange(nodes.shape[0]),np.arange(nodes.shape[1]))

# calculate distance of all points to centre
dist=np.sqrt((I-ci)**2+(J-cj)**2)




#Run simulation over density

for radius in np.range(1,10):
    l=np.where(dist<radius)
    k_1=np.ones(len(l[0]), dtype=int)
    k_2=np.ones(len(l[0]), dtype=int)*4
    new_1 = (*l, k_1)
    new_2 = (*l, k_2)
    nodes[new_1] = 1
    nodes[new_2] = 1
    
    

# arr = []
# # arr_k = []
# for kappa, i in zip(np.arange(-8, 8.1, 0.1), range(0,200)):
# #     arr_k.append(kappa)
#     arr.append([])
#     kappa = round(kappa,1)
# #     arr_i = []
#     for theta, j in zip(np.arange(0, 1.04, 0.05), range(0,30)): 
#         #new lattice
#         nodes = np.zeros((100,100,8))
#         nodes[new_1] = 1
#         nodes[new_2] = 1
#         #run
#         theta = round(theta,2)
# #         arr_i.append(theta)
#         lgca = get_lgca(interaction='go_or_grow', restchannels=4, kappa=kappa, theta=theta, nodes=nodes, 
#                         geometry='square')
#         lgca.timeevo(timesteps=100)
#         arr[i].append(lgca.nodes[:,:,4:].sum()) #summing rest cells

# n_r_k_theta = np.flipud(arr)

# print("Done!")

SyntaxError: invalid syntax (1723906914.py, line 20)

In [11]:
import numpy as np 
import matplotlib.pyplot as plt
# specify circle parameters: centre ij and radius
nodes = np.zeros((100,100,8))
ci,cj=50,50
cr=10

# Create index arrays to z
I,J=np.meshgrid(np.arange(nodes.shape[0]),np.arange(nodes.shape[1]))

# calculate distance of all points to centre
dist=np.sqrt((I-ci)**2+(J-cj)**2)

# Assign value of 1 rest and moving to those points where dist<cr:
l=np.where(dist<cr)
k_1=np.ones(len(l[0]), dtype=int)
k_2=np.ones(len(l[0]), dtype=int)*4
new_1 = (*l, k_1)
new_2 = (*l, k_2)
nodes[new_1] = 1
nodes[new_2] = 1

nodes_2 = np.sum(nodes, axis = 2)
print(nodes_2/8)
nodes_2 = nodes_2/8
nodes_2.sum()/10000


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


0.007625

### import numpy as np 
import matplotlib.pyplot as plt

# specify circle parameters: centre ij and radius
nodes = np.zeros((100,100,8))
ci,cj=50,50
cr=10

# Create index arrays to z
I,J=np.meshgrid(np.arange(nodes.shape[0]),np.arange(nodes.shape[1]))

# calculate distance of all points to centre
dist=np.sqrt((I-ci)**2+(J-cj)**2)

# Assign value of 1 rest and moving to those points where dist<cr:
l=np.where(dist<cr)
k_1=np.ones(len(l[0]), dtype=int)
k_2=np.ones(len(l[0]), dtype=int)*4
new_1 = (*l, k_1)
new_2 = (*l, k_2)
nodes[new_1] = 1
nodes[new_2] = 1

nodes.sum()/2


In [10]:
for x in range(1,10):
    print(x)

1
2
3
4
5
6
7
8
9
