In [3]:
import numpy as np
import matplotlib.pyplot as plt

x, y = np.meshgrid(range(15),range(6))
v = np.random.rand(len(x.flatten()))

In [15]:
print(v.shape)

(90,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14])

In [23]:
for x, i in zip(np.arange(-8, 8, 0.1), range(0,161)):
  print(round(x,1), i)

-8.0 0
-7.9 1
-7.8 2
-7.7 3
-7.6 4
-7.5 5
-7.4 6
-7.3 7
-7.2 8
-7.1 9
-7.0 10
-6.9 11
-6.8 12
-6.7 13
-6.6 14
-6.5 15
-6.4 16
-6.3 17
-6.2 18
-6.1 19
-6.0 20
-5.9 21
-5.8 22
-5.7 23
-5.6 24
-5.5 25
-5.4 26
-5.3 27
-5.2 28
-5.1 29
-5.0 30
-4.9 31
-4.8 32
-4.7 33
-4.6 34
-4.5 35
-4.4 36
-4.3 37
-4.2 38
-4.1 39
-4.0 40
-3.9 41
-3.8 42
-3.7 43
-3.6 44
-3.5 45
-3.4 46
-3.3 47
-3.2 48
-3.1 49
-3.0 50
-2.9 51
-2.8 52
-2.7 53
-2.6 54
-2.5 55
-2.4 56
-2.3 57
-2.2 58
-2.1 59
-2.0 60
-1.9 61
-1.8 62
-1.7 63
-1.6 64
-1.5 65
-1.4 66
-1.3 67
-1.2 68
-1.1 69
-1.0 70
-0.9 71
-0.8 72
-0.7 73
-0.6 74
-0.5 75
-0.4 76
-0.3 77
-0.2 78
-0.1 79
-0.0 80
0.1 81
0.2 82
0.3 83
0.4 84
0.5 85
0.6 86
0.7 87
0.8 88
0.9 89
1.0 90
1.1 91
1.2 92
1.3 93
1.4 94
1.5 95
1.6 96
1.7 97
1.8 98
1.9 99
2.0 100
2.1 101
2.2 102
2.3 103
2.4 104
2.5 105
2.6 106
2.7 107
2.8 108
2.9 109
3.0 110
3.1 111
3.2 112
3.3 113
3.4 114
3.5 115
3.6 116
3.7 117
3.8 118
3.9 119
4.0 120
4.1 121
4.2 122
4.3 123
4.4 124
4.5 125
4.6 126
4.7 127
4.8 1

In [27]:
x = list(range(1,10))
print(x)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
x[4:]

[5, 6, 7, 8, 9]

In [47]:
nodes = np.zeros((5,5,8))
ci,cj=2,2
cr=2

# Create index arrays to z
I,J=np.meshgrid(np.arange(nodes.shape[0]),np.arange(nodes.shape[1]))

# calculate distance of all points to centre
dist=np.sqrt((I-ci)**2+(J-cj)**2)

# Assign value of 1 to those points where dist<cr:
nodes[np.where(dist<cr),0,0]=1
nodes[np.where(dist<cr),0,4]=1
print(nodes)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]
